version: '3'
services:
  websphere:
    build: websphere-traditional
    ports:
      - "9043:9043"
      - "9443:9443"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
  db2:
    build: db2
    ports:
      - "50000:50000"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
  kerberos:
    image: "gcavalcante8808/krb5-server"
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=localhost
      - KRB5_PASS=password