version: '3'
volumes:
    krb5kdc-data:
services:
  websphere:
    build: websphere-traditional
    ports:
      - "9043:9043"
      - "9443:9443"
      - "9080:9080"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
    networks:
      krbnet:
        ipv4_address: 10.5.0.2
#  liberty:
#    build: liberty
#    ports:
#      - "9080:9080"
#      - "443:443"
#    environment:
#      - KRB5_REALM=EXAMPLE.COM
#      - KRB5_KDC=kerberos
#    depends_on: 
#      - "db2"
#    volumes:
#    - /Users/mjswatos/docker/logs:/logs
  db2:
    build: db2
    ports:
      - "50000:50000"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
    privileged: True
    depends_on: 
      - "kerberos"
    networks:
      krbnet:
        ipv4_address: 10.5.0.5
  kerberos:
    build: kdc-server
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=localhost
      - KRB5_PASS=password
    volumes:
      - krb5kdc-data:/var/lib/krb5kdc
    networks:
      krbnet:
        ipv4_address: 10.5.0.9
networks:
  krbnet:   
    ipam:
      config:
        - subnet: 10.5.0.0/16