version: '3'
volumes:
    krb5kdc-data:
services:
  websphere:
    build: websphere-traditional
    ports:
      - "9043:9043"
      - "9443:9443"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
  db2:
    build: db2
    ports:
      - "50000:50000"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
    privileged: True
  kerberos:
    build: kdc-server
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=localhost
      - KRB5_PASS=password
    volumes:
      - krb5kdc-data:/var/lib/krb5kdc